"""
BugKit v4 — Report Generator

Produces professional bug bounty reports:
  • Markdown (default)
  • HTML (with severity chart, embedded screenshots)
  • JSON (machine-readable evidence pack)

Every finding includes:
  title · severity · confidence · affected endpoint
  evidence · raw HTTP · curl PoC · repro steps
  impact · remediation · CWE · CVSS
"""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import List, Optional

from jinja2 import Environment, BaseLoader

from core import logger
from db import queries
from db.models import Finding, Target


# ── Jinja2 templates ───────────────────────────────────────────────────

MARKDOWN_TMPL = """\
# {{ target.domain }} — BugKit v4 Security Report

Generated: {{ now }}  
Tool: BugKit v4 / private security assessment

---

## Executive Summary

| Severity | Count |
|----------|-------|
| 🔴 CRITICAL | {{ counts.CRITICAL }} |
| 🟠 HIGH     | {{ counts.HIGH }} |
| 🟡 MEDIUM   | {{ counts.MEDIUM }} |
| 🔵 LOW      | {{ counts.LOW }} |
| ⚪ INFO     | {{ counts.INFO }} |

**Total Findings:** {{ findings|length }}

---

## Findings

{% for f in findings %}
### [{{ loop.index }}] {{ f.title }}

| Field        | Value |
|-------------|-------|
| **Severity** | {{ f.severity }} |
| **Confidence** | {{ f.confidence }} |
| **Module** | {{ f.module }} |
| **URL** | `{{ f.url }}` |
| **Method** | {{ f.method or "GET" }} |
{% if f.parameter %}| **Parameter** | `{{ f.parameter }}` |{% endif %}
{% if f.cwe %}| **CWE** | {{ f.cwe }} |{% endif %}
{% if f.cvss %}| **CVSS** | {{ f.cvss }} |{% endif %}

**Detail:**  
{{ f.detail or "—" }}

**Evidence:**  
```
{{ f.evidence or "—" }}
```

{% if f.payload %}
**Payload:**  
```
{{ f.payload }}
```
{% endif %}

{% if f.curl_poc %}
**PoC (curl):**  
```bash
{{ f.curl_poc }}
```
{% endif %}

{% if f.raw_request %}
**Raw Request:**  
```http
{{ f.raw_request }}
```
{% endif %}

**Impact:**  
{{ f.impact or "—" }}

**Remediation:**  
{{ f.remediation or "—" }}

{% if f.repro_steps %}
**Reproduction Steps:**  
{{ f.repro_steps }}
{% endif %}

---
{% endfor %}

*Report generated by BugKit v4 — private use only.*
"""

HTML_TMPL = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{{ target.domain }} — BugKit v4 Report</title>
<style>
  body { font-family: -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;
         background:#0d1117; color:#c9d1d9; max-width:960px; margin:0 auto; padding:2rem; }
  h1,h2,h3 { color:#f0f6fc; }
  a { color:#58a6ff; }
  table { border-collapse:collapse; width:100%; margin:1rem 0; }
  th,td { border:1px solid #30363d; padding:.5rem .75rem; text-align:left; }
  th { background:#161b22; color:#8b949e; font-size:.8rem; text-transform:uppercase; }
  .CRITICAL { color:#ff7b72; } .HIGH { color:#ffa657; }
  .MEDIUM { color:#e3b341; } .LOW { color:#79c0ff; } .INFO { color:#8b949e; }
  .badge { display:inline-block; padding:.15rem .5rem; border-radius:4px;
           font-size:.75rem; font-weight:600; }
  .badge.CRITICAL { background:#3d1a1a; color:#ff7b72; }
  .badge.HIGH     { background:#3d2a1a; color:#ffa657; }
  .badge.MEDIUM   { background:#3d3300; color:#e3b341; }
  .badge.LOW      { background:#1a2a3d; color:#79c0ff; }
  .badge.INFO     { background:#21262d; color:#8b949e; }
  pre { background:#161b22; border:1px solid #30363d; border-radius:6px;
        padding:1rem; overflow-x:auto; font-size:.8rem; white-space:pre-wrap; }
  .finding-card { background:#161b22; border:1px solid #30363d;
                  border-radius:8px; padding:1.5rem; margin:1.5rem 0; }
  .finding-card h3 { margin-top:0; }
  .summary-grid { display:grid; grid-template-columns:repeat(5,1fr); gap:.75rem; margin:1.5rem 0; }
  .stat { background:#161b22; border:1px solid #30363d; border-radius:6px;
          padding:1rem; text-align:center; }
  .stat-num { font-size:2rem; font-weight:700; }
  .stat-lbl { font-size:.8rem; color:#8b949e; }
  details > summary { cursor:pointer; color:#58a6ff; }
  .toc a { display:block; padding:.25rem 0; }
</style>
</head>
<body>
<h1>🎯 {{ target.domain }}</h1>
<p style="color:#8b949e">BugKit v4 Security Report &nbsp;·&nbsp; {{ now }}</p>

<h2>Executive Summary</h2>
<div class="summary-grid">
  {% for sev, cls in [('CRITICAL','CRITICAL'),('HIGH','HIGH'),('MEDIUM','MEDIUM'),('LOW','LOW'),('INFO','INFO')] %}
  <div class="stat">
    <div class="stat-num {{ cls }}">{{ counts[sev] }}</div>
    <div class="stat-lbl">{{ sev }}</div>
  </div>
  {% endfor %}
</div>

<h2>Table of Contents</h2>
<div class="toc">
{% for f in findings %}
  <a href="#f{{ loop.index }}"><span class="badge {{ f.severity }}">{{ f.severity }}</span> {{ f.title }}</a>
{% endfor %}
</div>

<h2>Findings</h2>
{% for f in findings %}
<div class="finding-card" id="f{{ loop.index }}">
  <h3>
    <span class="badge {{ f.severity }}">{{ f.severity }}</span>&nbsp;
    {{ f.title }}
  </h3>
  <table>
    <tr><th>URL</th><td><code>{{ f.url }}</code></td></tr>
    <tr><th>Method</th><td>{{ f.method or "GET" }}</td></tr>
    {% if f.parameter %}<tr><th>Parameter</th><td><code>{{ f.parameter }}</code></td></tr>{% endif %}
    <tr><th>Module</th><td>{{ f.module }}</td></tr>
    <tr><th>Confidence</th><td>{{ f.confidence }}</td></tr>
    {% if f.cwe %}<tr><th>CWE</th><td><a href="https://cwe.mitre.org/data/definitions/{{ f.cwe[4:] }}.html">{{ f.cwe }}</a></td></tr>{% endif %}
    {% if f.cvss %}<tr><th>CVSS</th><td>{{ f.cvss }}</td></tr>{% endif %}
  </table>

  {% if f.detail %}<h4>Detail</h4><p>{{ f.detail }}</p>{% endif %}
  {% if f.evidence %}<h4>Evidence</h4><pre>{{ f.evidence }}</pre>{% endif %}
  {% if f.payload %}<h4>Payload</h4><pre>{{ f.payload }}</pre>{% endif %}

  {% if f.curl_poc %}
  <details>
    <summary>▸ PoC (curl)</summary>
    <pre>{{ f.curl_poc }}</pre>
  </details>
  {% endif %}

  {% if f.raw_request %}
  <details>
    <summary>▸ Raw HTTP Request</summary>
    <pre>{{ f.raw_request }}</pre>
  </details>
  {% endif %}

  {% if f.raw_response %}
  <details>
    <summary>▸ Raw HTTP Response (truncated)</summary>
    <pre>{{ f.raw_response }}</pre>
  </details>
  {% endif %}

  {% if f.impact %}<h4>Impact</h4><p>{{ f.impact }}</p>{% endif %}
  {% if f.remediation %}<h4>Remediation</h4><p>{{ f.remediation }}</p>{% endif %}

  {% if f.repro_steps %}
  <h4>Reproduction Steps</h4>
  <pre>{{ f.repro_steps }}</pre>
  {% endif %}
</div>
{% endfor %}

<hr style="border-color:#30363d; margin-top:3rem">
<p style="color:#8b949e;font-size:.8rem">
  Generated by BugKit v4 — private security assessment tool — {{ now }}
</p>
</body>
</html>
"""


class ReportGenerator:
    """
    Generate a complete bounty report from DB findings.

    Usage:
        gen = ReportGenerator()
        gen.generate(target="example.com", fmt="html", output_path=Path("report.html"))
    """

    def __init__(self) -> None:
        # This environment renders BOTH the Markdown and HTML templates.
        # Findings frequently contain the attacker payloads you injected
        # during testing (f.evidence, f.payload, f.curl_poc, f.raw_request).
        # Those must stay unescaped for Markdown (raw text inside code
        # fences) but MUST be escaped for HTML, or opening your own report
        # in a browser can execute a stored XSS payload you found. Jinja's
        # autoescape is an Environment-level setting, so we keep the
        # original unescaped env for Markdown/JSON and add a second,
        # escaped one used only for the HTML template.
        self._env      = Environment(loader=BaseLoader(), autoescape=False)  # nosec B701 - Markdown/JSON only, never HTML_TMPL. See self._env_html below.
        self._env_html = Environment(loader=BaseLoader(), autoescape=True)

    def generate(
        self,
        target:      str,
        fmt:         str = "md",
        output_path: Optional[Path] = None,
        severity:    Optional[str] = None,
        module:      Optional[str] = None,
        finding_id:  Optional[int] = None,
    ) -> str:
        t = queries.get_target(target)
        if not t:
            logger.err(f"Target '{target}' not found.")
            return ""

        if finding_id:
            with queries.get_db() as db:
                from db.models import Finding as FindingModel
                findings = db.query(FindingModel).filter_by(id=finding_id).all()
        else:
            findings = queries.get_findings(
                target_id = t.id,
                module    = module,
                severity  = severity,
            )

        if not findings:
            logger.warn("No findings to report.")
            return ""

        counts = {sev: 0 for sev in ("CRITICAL","HIGH","MEDIUM","LOW","INFO")}
        for f in findings:
            counts[f.severity] = counts.get(f.severity, 0) + 1

        ctx = {
            "target":   t,
            "findings": findings,
            "counts":   counts,
            "now":      datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        }

        if fmt == "html":
            tmpl   = self._env_html.from_string(HTML_TMPL)
            output = tmpl.render(**ctx)
        elif fmt == "json":
            output = self._to_json(t, findings, counts)
        else:
            tmpl   = self._env.from_string(MARKDOWN_TMPL)
            output = tmpl.render(**ctx)

        if output_path:
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(output, encoding="utf-8")
            logger.ok(f"Report written: {output_path}  ({len(findings)} findings)")
        else:
            print(output)

        return output

    def _to_json(self, target: Target, findings: List[Finding], counts: dict) -> str:
        data = {
            "target":    target.domain,
            "generated": datetime.utcnow().isoformat(),
            "summary":   counts,
            "findings": [
                {
                    "id":          f.id,
                    "title":       f.title,
                    "severity":    f.severity,
                    "confidence":  f.confidence,
                    "module":      f.module,
                    "url":         f.url,
                    "method":      f.method,
                    "parameter":   f.parameter,
                    "payload":     f.payload,
                    "evidence":    f.evidence,
                    "curl_poc":    f.curl_poc,
                    "detail":      f.detail,
                    "impact":      f.impact,
                    "remediation": f.remediation,
                    "cwe":         f.cwe,
                    "cvss":        f.cvss,
                    "tags":        f.tag_list,
                    "created_at":  f.created_at.isoformat(),
                }
                for f in findings
            ],
        }
        return json.dumps(data, indent=2, default=str)
